### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by lets00** [veramolabs/veramo-react-app-tutorial#2]
Hi everyone,

When I've tried running this example, I receive this error message:

![image](https://github.com/veramolabs/veramo-react-app-tutorial/assets/5157983/f92cbef3-1e7e-460f-87e1-4ce9846e4560)

Verifying this URL: https://goerli.infura.io/v3/33aab9e0334c44b0a2e0c57c15302608 , I'm receving a 410 error status code with this JSON response:

```json
{
  "id":null,
  "error": {
    "code":-32601,
    "message":"Network decommissioned, please use Sepolia instead",
    "data": {
      "see":"https://www.infura.io/blog/post/deprecation-notice-for-all-infura-supported-goerli-endpoints"
    }
  }
}

```

I don't know what is happening and what should I do to run this project properly.

My specs:
Node version: v20.12.2
NPM version: 10.5.0
SO: Ubuntu 20.04 LTS

**Comment by iamtmehdi** [comment]
The Goerli testnet is now deprecated by the Infura API. These references need to be updated to the Sepolia testnet.

I have submitted a PR to resolve the issue. Essentially, the Goerli DID URL in line 11 of `src/App.tsx` in line needs to be updated to a Sepolia DID URL.

Change `didUrl: 'did:ethr:goerli:0x6acf3bb1ef0ee84559de2bc2bd9d91532062a730',` to `didUrl: 'did:ethr:sepolia:0x02bd224258f3b0ae8fa5388342783d9697dac9133eb476c7946eeed9ac7b864ce1',` and it should resolve the issue.

edit: You also need to update `ethr-did-resolver` package to the latest to support `did:ethr:sepolia` method, which can be done via `yarn upgrade ethr-did-resolver@^10.1.5`.
